[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
trump_token = "9squCvWC9xQiGYo9JFhaKULVaV3eTJ4e7JNRyHKFxLCY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/km-00012/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
